### ISSUE TITLE
Unwanted line appears on figure hover

### ISSUE THREAD

**Issue by jibarozzo** [jibarozzo/bolaponte_website#3]
There's an unwanted line appearing when hovering over figures on the website. This is likely caused by the global link hover styles in the theme.scss file that add an underline effect to all anchor elements.

The issue is probably coming from this CSS rule:
```scss
a:not(.nav-link):not(.navbar-brand):not(.btn):after {
  content: '';
  position: absolute;
  bottom: -2px;
  left: 0;
  width: 0;
  height: 2px;
  background-color: $accent;
  transition: width 0.3s ease;
}

a:not(.nav-link):not(.navbar-brand):not(.btn):hover:after {
  width: 100%;
}
```

This rule targets all anchor elements and adds a hover underline effect, but it's not excluding figure links/lightbox triggers.

**Steps to reproduce:**
1. Navigate to a page with figures/images
2. Hover over any figure
3. Observe unwanted line appearing

**Expected behavior:**
Figures should not show the hover underline effect

**Suggested fix:**
Add `.lightbox` or figure-related selectors to the `:not()` exclusion list in the hover effect CSS rule.
